openapi: 3.0.2
info:
  title: Your API
  version: 1.0.0
paths:
  /your_endpoint:
    get:
      summary: Your Endpoint Summary
      description: Your Endpoint Description
      parameters:
        - name: days_before
          in: query
          description: Number of days before (optional)
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 60 # Adjust as needed
      responses:
        "200":
          description: Successful response
